esphome:
  name: distance-sensor

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "WysYoTm7RJa+yv9uNfgXQtZBq1XlLSxFfbJPQdJlisE="

ota:
  password: "6e991a99b919d063ba40f958796f21e1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Distance-Sensor Fallback Hotspot"
    password: "CQ8uezqyIxR8"

captive_portal:

sensor:
  - platform: ultrasonic
    trigger_pin: D1
    echo_pin: D2
    name: "Ultrasonic Sensor"
    update_interval: 0.1s
    unit_of_measurement: "cm"
    filters:
      - median:
          window_size: 6
          send_every: 3
          send_first_at: 3
      - multiply: 100

light:
  - platform: status_led
    name: "Garage Distance Status Indicator"
    pin: 
      number: D4
      inverted: true