esphome:
  name: stoplight

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "qt7iJf6TXaDgYA8clDgc3Ri8I6J8hrmXn6zJ3tQmT4w="

ota:
  password: "950e611b356fdc2b01c5b485799ed4cf"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Stoplight Fallback Hotspot"
    password: "FjwQsTs7NJez"

captive_portal:
    
light:
  - platform: binary
    name: "Garage Green Light"
    output: light_output_green
  - platform: binary
    name: "Garage Yellow Light"
    output: light_output_yellow
  - platform: binary
    name: "Garage Red Light"
    output: light_output_red
  - platform: status_led
    name: "Garage Stoplight Status Indicator"
    pin: 
      number: D4
      inverted: true

output:
  - id: light_output_green
    platform: gpio
    pin: D1
  - id: light_output_yellow
    platform: gpio
    pin: D2
  - id: light_output_red
    platform: gpio
    pin: D3