alias: Door Sensor > Stoplight All Off
description: ""
trigger:
  - type: turned_off
    platform: device
    device_id: 6628b5f7c3e24b93dc9c6f117d1280a7
    entity_id: binary_sensor.garage_door_sensor
    domain: binary_sensor
condition: []
action:
  - repeat:
      count: "2"
      sequence:
        - type: turn_off
          device_id: eba45fac4c4764fd905016f1d2670fbe
          entity_id: light.garage_green_light
          domain: light
        - type: turn_off
          device_id: eba45fac4c4764fd905016f1d2670fbe
          entity_id: light.garage_yellow_light
          domain: light
        - type: turn_off
          device_id: eba45fac4c4764fd905016f1d2670fbe
          entity_id: light.garage_red_light
          domain: light
        - delay:
            hours: 0
            minutes: 0
            seconds: 0
            milliseconds: 400
mode: single
