esphome:
  name: door-sensor
 
esp8266:
  board: d1_mini
 
# Enable logging
logger:
 
# Enable Home Assistant API
api:
  encryption:
    key: "BtcKVNjdSxtHiKddwcRkHgLfaMC27iIG/czfviO/9Fo="
 
ota:
  password: "473fbd7d2a3102dce8b89a788fa8f39f"
 
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
 
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Door-Sensor Fallback Hotspot"
    password: "MYCPCgnvtIy1"
 
captive_portal:
   
binary_sensor:
  - platform: gpio
    name: "Garage Door Sensor"
    pin:
      number: D1
      mode:
        input: true
        pullup: true
 
switch:
  - platform: gpio
    name: "Relay Switch"
    pin: D1
 
light:
  - platform: status_led
    name: "Garage Door Status Indicator"
    pin:
      number: D4
      inverted: true